Feature/log validate store dau
OpenLXP/openlxp-xia-dau pull request #2
Opened 2021-02-01 20:36 UTC by SHGODE

Adding changes for ETL ( updating metadata_ledger table) 

@mattdrayer

2021-02-01 21:14 UTC, mattdrayer requested changes
Great first pass!  I've left a lot of comments mainly pointing out refactoring opportunities.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/management/commands/source_validation.py
> +    """Django command to validate DAU data from given AWS environment"""
Great use of Docstring!  One thing to keep in mind is that we know the DAU data source will likely not be hosted in AWS -- we should protect the system from change as much as possible by encapsulating the AWS-specific implementation in its own module/class/function/etc.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/management/commands/source_validation.py
> +        logger.info("Source validation completed")
Recommend being more descriptive than "Source" -- perhaps there is a property/setting which is referenced in each Agent implementation which describes the name of the Agent.  If we want to provide the System Operator with some control/flexibility it could be stored in the XIAConfiguration model or a settings file versus the code.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/management/commands/target_validation.py
> +        s3 = boto3.resource('s3')
We should encapsulate all of the work to create an S3 object, etc. into its own helper class or at least a module containing the AWS helper functions.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/management/commands/target_validation.py
> +        required_dict = {}
This pattern (and much of the overall function) is replicated throughout the implementation -- recommend generalizing it to a helper function (ie, [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)'ing the code) and referencing the helper where needed.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/management/commands/waitdb.py
> +    help = "Checks database connection"
Is this for Docker container initialization?  If so we should include that context.  Please use a Docstring.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/management/commands/waitdb.py
> +        self.stdout.write(self.style.SUCCESS("Database connections successful"))
"connections" -> "connection".  Also looks like you need to add a newline at the end of the file.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/migrations/0001_initial.py
> +class Migration(migrations.Migration):
We should be able to revise the initial implementation multiple times, until the first official version of the agent has been deployed to production and the database contains information that cannot be lost.  There is a way to "squash" migrations which is the easiest way to do this.

2021-02-01 21:14 UTC, mattdrayer commented on app/core/models.py
> +        """Returns the url to access a particular author instance."""
Great use of Docstrings here!

2021-02-01 21:14 UTC, mattdrayer commented on app/manage.py
> +    main()
Missing newline at end of file.

2021-02-01 21:14 UTC, mattdrayer commented on nginx.default
>  }
Missing newline at end of file.

2021-02-01 21:14 UTC, mattdrayer commented on start-server.sh
>  nginx -g "daemon off;"
Missing newline at end of file.

2021-02-01 22:34 UTC, KarenAJ commented on app/core/management/commands/load_dau.py
> +                        key_course = dau_dict[k][k1].get('CourseCode')
We followed the schema for transformation given by Vishal. Open to suggestions

2021-02-01 22:40 UTC, KarenAJ commented on app/core/management/commands/waitdb.py
> +    help = "Checks database connection"
@jdiouf  Can you please look into this

2021-02-02 02:14 UTC, mattdrayer commented on app/core/management/commands/load_dau.py
> +        """Setting record_status & deleted_date for updated record"""
Arg, my bad, I should have been more clear -- Docstrings are only necessary for annotating function descriptions -- in all other cases it is fine to use normal commenting syntax.

2021-02-02 03:25 UTC, mattdrayer requested changes
I've left a few more suggestions/recommendations - overall I think we should reorganize the commands and operations being performed to reflect the asynchronous Extract/Validate/Transform/Validate/Load (EVTVL) workflows -- this pattern will be consistent across all XIAs with the specific implementations varying.  The command structure could look like this:

`app/core/management/commands/extract_source_metadata.py`
`app/core/management/commands/validate_source_metadata.py`
`app/core/management/commands/transform_metadata.py`
`app/core/management/commands/validate_target_metadata.py`
`app/core/management/commands/load_target_metadata.py`

If we want to have a top-level strategy-style command that executes the entire EVTVL orchestration that is fine, but it should be a separate process.

Also we should have a module which encapsulates the AWS-specific interactions so we do not have references to Boto, S3, etc. distributed throughout the scripts -- it could be named `aws.py` and the commands could reference it.

2021-02-02 03:25 UTC, mattdrayer commented on app/core/management/commands/target_validation.py
>          dau_target_json_content = dau_target_json.get()['Body'].read().decode('utf-8')
We can eliminate `dau` code prefixes and suffixes because we already know we are working with the DAU XIA implementation.  This will help to identify commonalities within the implementation -- which can be DRY'ed into helper methods -- as well as across the implementation -- which can be DRY'ed into the `openlxp-xia` repository/package.

2021-02-02 14:28 UTC, jdiouf commented on app/app/settings.py
> +            'level': 'INFO',
Hey Matt, I believe setting INFO as the level gives us all the other log levels below it like WARNING and ERROR

2021-02-02 14:30 UTC, mattdrayer commented on app/app/settings.py
> +            'level': 'INFO',
Cool - TIL!

2021-02-02 15:27 UTC, mattdrayer commented on app/core/management/commands/load_dau.py
> +                key_value = '_'.join([str(key_course), key_source])
Recommend pre-pending the source tag to the key, so that for example all DAU source keys begin with `DAU_`

2021-02-02 15:28 UTC, mattdrayer commented on app/core/migrations/0001_initial.py
> +                ('unique_record_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
Recommend making this a UUID field, unless the team feels that it makes more sense to have an autoincrementing integer -- @VishalECC, thoughts?

2021-02-02 16:01 UTC, VishalECC commented on app/core/migrations/0001_initial.py
> +                ('unique_record_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
I agree. We did think about coming up with the UUID but then went autoincrementing given it can still uniquely identify the record. To make it UUID, we can use the metadata hash and extracted date column to come up with UUID.

2021-02-02 16:44 UTC, mattdrayer commented on app/core/migrations/0001_initial.py
> +                ('unique_record_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
I recommend going with the python UUID package: https://docs.python.org/3/library/uuid.html, specifically `uuid4()`

2021-02-02 21:30 UTC, mattdrayer commented on docker-compose.yml
> +      - C:/Users/shgode/Documents/dockerRun/cacert.pem:/etc/ssl/certs/ca-certificates.pem
If possible we should extract this file path into an environment variable since it is specific to your workstation.

2021-02-02 22:40 UTC, KarenAJ commented on app/core/management/commands/source_validation.py
> +        logger.info("Source validation completed")
To make this work does it make sense to just get the Agent name from the operator from the admin page? @mattdrayer

2021-02-02 22:55 UTC, mattdrayer commented on app/core/management/commands/source_validation.py
> +        logger.info("Source validation completed")
Yes I think that makes sense.

2021-02-03 16:00 UTC, jdiouf reviewed
Hey @mattdrayer, these are starter tests I added to guide the rest of the team. The tests that need a database connection fail due to the timing with the docker containers so I tagged them with 'Integration' so we can run them separately from the unit tests. Couldn't seem to find a standard when it comes to docker + django testing.

2021-02-03 20:01 UTC, mattdrayer requested changes
We are on the right track!  A few small comments for this particular commit.

2021-02-03 20:01 UTC, mattdrayer commented on app/core/management/commands/validate_source_metadata.py
> +        s3 = boto3.resource('s3')
Recommend generalizing the environment-specific information into a separate module, such as `aws.py` with helper methods such as`read_metadata()`, 'write_metadata()', etc.

2021-02-03 20:05 UTC, mattdrayer commented on start-app.sh
> +./start-server.sh
Need a newline at end of file.

2021-02-03 23:02 UTC, KarenAJ commented on app/core/management/commands/extract_source_metadata.py
> +        # MetadataLedger load from source
Is it ok if we still write to local for the purpose of uploading to s3? I have made changes to not require reading it again for storing purposes. @mattdrayer

2021-02-04 03:15 UTC, mattdrayer commented on app/core/management/commands/extract_source_metadata.py
> +        # MetadataLedger load from source
I guess I don’t see a reason to write a local temp file unless we need to do it as part of transmitting data with Boto/S3 — if that’s the case we should encapsulate the implementation within the suggested aws.py module.  We are already persisting the transformed records in the MetadataLedger so we should be reading from there in order to transmit the data, anyway.

2021-02-04 14:23 UTC, KarenAJ commented on app/core/management/commands/extract_source_metadata.py
> +        # MetadataLedger load from source
True Matt, we'll work on making those changes

2021-02-04 14:40 UTC, mattdrayer commented on app/core/management/commands/extract_source_metadata.py
> +        # MetadataLedger load from source
Rather than `aws.py` it probably makes more sense to name the file `xsr_client.py` (XSR -> Experience Source Repository) since the implementation will vary from one XIA to the next, but we will always want to have a module which encapsulates the specific details around communicating with the XSR.

2021-02-05 01:21 UTC, mattdrayer commented on app/core/models.py
> +    extracted_date = models.DateTimeField(auto_now_add=True)
We should be consistent with the naming of the date fields -- for example we could do:

`source_metadata_extraction_date`
`source_metadata_validation_date`
`source_metadata_transformation_date`
`target_metadata_validation_date`
`target_metadata_transmission_date`

2021-02-05 01:23 UTC, mattdrayer commented on app/core/models.py
> +    deleted_date = models.DateTimeField(blank=True, null=True)
`metadata_record_deletion_date`, actually, we are "inactivating" in the case of our ledger (ie, nothing is ever really deleted), so we could probably go with `metadata_record_inactivation_date`

2021-02-05 01:23 UTC, mattdrayer commented on app/core/models.py
> +    unique_record_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
What do you think about `metadata_record_uuid`?

2021-02-05 01:27 UTC, mattdrayer commented on app/core/models.py
> +    extracted_date = models.DateTimeField(auto_now_add=True)
And since I'm a total nerd, if we could alphabetize the fields aside from the unique identifier that would be great 😺

2021-02-05 01:28 UTC, mattdrayer commented on app/core/models.py
> +    record_status = models.TextField()
`record_active_status` might make more sense -- also this is a TextField -- we should probably constrain to a specific set of `choices`

2021-02-05 01:29 UTC, mattdrayer commented on app/core/models.py
> +    target_metadata_hash = models.TextField(max_length=200)
Generally speaking if we are constraining the length to less than 255 characters we should use a CharField and not a TextField.

2021-02-05 01:30 UTC, mattdrayer commented on app/core/models.py
> +    target_metadata_validation = models.CharField(max_length=10, blank=True, choices=METADATA_VALIDATION_CHOICES)
target_metadata_validation_status ?

2021-02-05 01:31 UTC, mattdrayer commented on app/core/models.py
> +    source_metadata_validation = models.CharField(max_length=10, blank=True, choices=METADATA_VALIDATION_CHOICES)
source_metadata_validation_status ?

2021-02-05 01:32 UTC, mattdrayer commented on app/core/models.py
> +    source_metadata = models.JSONField(blank=True)
My ONLY problem with this is that we can't always assume the source metadata will be provided in JSON format -- it may make sense to convert this into a TextField.  Although since each XIA is implemented according to the specification of the XSR source schema perhaps it's alright -- what do you think?

2021-02-05 01:35 UTC, mattdrayer commented on start-app.sh
> +# start-server.sh
Looks like this commented-out line can be removed, but we'll need to keep the sha-bang on line 1

2021-02-05 01:35 UTC, mattdrayer commented on app/core/tests/test_models_unit.py
> +        self.assertEqual(xiaConfig.target_validation_schema, 'DAU_To_P2881_Target_Validate_Schema.json')
need a newline at end of file

2021-02-05 01:38 UTC, mattdrayer commented on app/core/models.py
> +    source_file_name = models.CharField(default='DAU_Consolidated.csv', max_length=200,
As we've discussed this is only a temporary measure since the DAU agent will actually connect to the DAU web service in order to extract the metadata.

2021-02-05 01:39 UTC, mattdrayer commented on app/core/models.py
> +        """Returns the url to access a particular author instance."""
not sure what we mean by "author instance" here?

2021-02-05 01:39 UTC, mattdrayer commented on app/core/models.py
> +# from django.core.exceptions import ValidationError
Looks like we can remove this.

2021-02-05 01:42 UTC, mattdrayer commented on app/core/management/commands/extract_source_metadata.py
> +        write_metadata(data_file_name, std_source_df.to_json(orient='index'))
it's still not clear to me why we are writing to a file here?

2021-02-05 17:23 UTC, VishalECC commented on app/core/models.py
> +    record_status = models.TextField()
record_lifecycle_status

2021-02-09 15:23 UTC, mattdrayer requested changes
Getting close to the endzone!

2021-02-09 15:23 UTC, mattdrayer commented on Dockerfile
> +#COPY .pip_cache /opt/app/pip_cache/
If we don't need this commented-out line we should remove it.

2021-02-09 15:23 UTC, mattdrayer commented on app/core/management/commands/load_dau.py
> +from django.utils import timezone
Are we still planning on keeping this `load_dau.py` file?

2021-02-09 15:23 UTC, mattdrayer commented on app/core/management/commands/map_dau.py
> +import logging
Are we planning to keep this `map_day.py` file?

2021-02-09 15:23 UTC, mattdrayer commented on app/core/management/commands/source_validation.py
> +import hashlib
do we still need this module?

2021-02-09 15:23 UTC, mattdrayer commented on app/core/management/commands/target_validation.py
> +import hashlib
do we still need this module?

2021-02-09 15:23 UTC, mattdrayer commented on app/core/models.py
> +    source_schema = models.CharField(default='DAU_Source_Renaming_Schema.json', max_length=200,
let's rename this to `source_metadata_schema`, and change the default value to 'dau_source_metadata_schema.json'

2021-02-09 15:23 UTC, mattdrayer commented on app/core/models.py
> +    target_validation_schema = models.CharField(default='DAU_To_P2881_Target_Validate_Schema.json', max_length=200,
let's rename this to `target_metadata_schema`, and change the default value to 'p2881_target_metadata_schema.json'

2021-02-09 15:23 UTC, mattdrayer commented on app/core/models.py
> +    target_renaming_schema = models.CharField(default='DAU_To_P2881_Renaming_Schema.json', max_length=200,
I guess I'm just realizing now that I don't know what this model field is used for?

2021-02-09 15:23 UTC, mattdrayer commented on app/core/models.py
> +    source_validation_schema = models.CharField(default='DAU_Source_Validate_Schema.json', max_length=200,
What is the difference between `source_schema` and `source_validation_schema`?  It seems like we should only need one?

2021-02-09 15:23 UTC, mattdrayer commented on app/core/models.py
> +    source_file_name = models.CharField(default='DAU_Consolidated.csv', max_length=200,
Seems like this model field is a holdover from the Amazon S3 proxy -- we probably should hide this inside of `xsr_client.py` and make it a setting.

2021-02-09 15:23 UTC, mattdrayer commented on app/core/models.py
> +    source_schema_path = models.CharField(default='s3://dauxia/', max_length=200,
If we assume that each schema file could potentially live in a different location, we will need to have a corresponding path/URL field for each one -- either that or the model field IS the fully-qualified URL/path pointing to that resource, which probably makes more sense.

2021-02-09 17:01 UTC, KarenAJ commented on app/core/models.py
> +    source_file_name = models.CharField(default='DAU_Consolidated.csv', max_length=200,
Sure, the publisher detail is required to populate the P2881 column "CourseProviderName" in the target. So should that be hardcoded for each agent in the settings?

2021-02-09 17:07 UTC, KarenAJ commented on app/core/models.py
> +    source_validation_schema = models.CharField(default='DAU_Source_Validate_Schema.json', max_length=200,
The source_schema is a json to rename the columns from source and source_validation_schema contains the required and optional mapping for validation. Are they supposed to be in one json file? I did the simple 1 level mapping for the json schemas

2021-02-09 17:07 UTC, mattdrayer commented on app/core/models.py
> +    source_file_name = models.CharField(default='DAU_Consolidated.csv', max_length=200,
Are you referring to the `publisher` field?  I think we can keep that in order to populate `CourseProviderName` -- what information is in the `DAU_Consolidated.csv` file that the XIA needs?

2021-02-09 17:09 UTC, mattdrayer commented on app/core/models.py
> +    source_validation_schema = models.CharField(default='DAU_Source_Validate_Schema.json', max_length=200,
I guess I don't understand why we are renaming the columns from source -- shouldn't we simply be using the columns as they are?

2021-02-09 17:11 UTC, KarenAJ commented on app/core/models.py
> +    source_schema_path = models.CharField(default='s3://dauxia/', max_length=200,
I was under the impression this was to store the url where all our schemas would be at. So for now that is the bucket location. Not sure if my assumption was right though. @VishalECC please help clarify on this.

2021-02-09 17:12 UTC, KarenAJ commented on app/core/models.py
> +    source_file_name = models.CharField(default='DAU_Consolidated.csv', max_length=200,
@VishalECC Please do let me know your inputs on this too

2021-02-09 17:37 UTC, KarenAJ commented on app/core/models.py
> +    source_file_name = models.CharField(default='DAU_Consolidated.csv', max_length=200,
Yup sorry about that, I misunderstood. I'll work on adding that to the xsr_client.

2021-02-09 17:40 UTC, mattdrayer commented on app/core/models.py
> +    source_schema_path = models.CharField(default='s3://dauxia/', max_length=200,
I think it would be simpler to have each schema column value be the fully-qualified URI for the resource, instead of splitting things apart.

2021-02-09 17:41 UTC, KarenAJ commented on app/core/models.py
> +    source_validation_schema = models.CharField(default='DAU_Source_Validate_Schema.json', max_length=200,
Sure Matt, I guess in our present workflow we do that as the mapping to P2881 is with these renamed columns. I'll discuss that with @VishalECC and see if it is necessary.

2021-02-09 17:43 UTC, KarenAJ commented on app/core/models.py
> +    source_schema_path = models.CharField(default='s3://dauxia/', max_length=200,
Sure Matt, I'll follow up with @VishalECC and make the changes.

2021-02-09 17:51 UTC, KarenAJ commented on app/core/models.py
> +    target_renaming_schema = models.CharField(default='DAU_To_P2881_Renaming_Schema.json', max_length=200,
So as the mapping to target is a 2 level json file there is the process of mapping to the new P2881 target field name for the columns mapped and then further mapping to target section name. So to make it simple I used 2 json files and mapped them. Is that ok?

2021-02-09 18:11 UTC, mattdrayer commented on app/core/models.py
> +    target_renaming_schema = models.CharField(default='DAU_To_P2881_Renaming_Schema.json', max_length=200,
I feel like this is exposing too much of the P2881 implementation to the XIA in the form of System Operator knowledge -- it would be better to have a single file containing the nested JSON tree as its schema, even though that makes the parsing a bit more complex.  We need to keep in mind that some day the standard will be revised and possibly replaced completely.  If we have a single file then we can have a corresponding parse function that understands how to access and work with the file.

2021-02-09 18:52 UTC, KarenAJ commented on app/core/models.py
> +    target_renaming_schema = models.CharField(default='DAU_To_P2881_Renaming_Schema.json', max_length=200,
Sure Matt. On it!

2021-02-14 17:46 UTC, mattdrayer commented on app/core/models.py
>      source_validation_schema = models.CharField(
I think we can simply call this `source_metadata_schema` -- it will likely be used for more than validation at some point.

2021-02-14 17:47 UTC, mattdrayer commented on app/core/management/commands/transform_source_metadata.py
> +        target_metadata_schema = get_target_metadata_schema()
The call to `get_target_metadata_schema` can be moved into `read_target_metadata_schema`, which can be renamed to `get_target_metadata_for_transformation` similar to `get_source_metadata_for_transformation`

2021-02-14 17:51 UTC, mattdrayer commented on app/core/management/commands/validate_source_metadata.py
> +    for ind in range(len(source_data_dict)):
Performance optimization -- set a local variable to the value of `len(source_data_dict)` and reference that in the loop.  This avoids re-evaluation of `len(source_data_dict)` for each loop iteration.

2021-02-14 17:52 UTC, mattdrayer commented on app/core/management/commands/validate_source_metadata.py
> +        schema_data_dict = read_source_validation_schema(
Can move `get_source_validation_schema` into `read_source_validation_schema`

2021-02-15 19:59 UTC, mattdrayer commented on app/core/models.py
> +    target_validation_schema = models.CharField(
Did we lose the mapping schema reference?  It seems to me that we still need three key reference schemas:  source, target, and source-target mapping.  As we discussed we probably do not need additional "validation" schemas, since this is the point of the source + target reference schemas.

2021-02-15 20:08 UTC, KarenAJ commented on app/core/models.py
> +    target_validation_schema = models.CharField(
That makes sense, so I'll make a source_schema, source_target_mapping and a target_schema to replace the present names. Validation files would become the source/target schemas so that they can expand their purpose later.

2021-02-15 20:31 UTC, KarenAJ commented on app/core/management/commands/transform_source_metadata.py
> +    target_schema = target_schema.replace(
@mattdrayer While using this replace function, it does not replace values which are Null/None/np.Nan and instead would skip that mapping in the the process. So I had to replace all Null values to empty strings in the source metadata from the DB and that is how it is finally present in the target metadata. Is this fine?

2021-02-16 14:00 UTC, mattdrayer commented on app/core/management/commands/transform_source_metadata.py
> +    target_schema = target_schema.replace(
Are you sure that `replace()` is the correct operation to use here?  If we are working with dictionaries you might look at using `update()`

2021-02-17 17:19 UTC, KarenAJ commented on app/core/management/commands/transform_source_metadata.py
> +    target_schema = target_schema.replace(
Thanks for the suggestion @mattdrayer , on looking into update(), in our present code we are trying to change the "value" of the dictionary items with the value of another dictionary, mapping it using the fact that the value of one the dictionary to get replaced is the key of the other dictionary. With update I'm not sure if this would work unless it's probably added in a loop and manually switched.

source_metadata    source_target_mapping  result
{                              {                                       {
 a:b,                           x{                                     x{
 c:d,                               y:a,                                    y:b, 
}                                    z:c                                     z:d 
                                }}                                      }}
Update() seems really good though as the null/none values are reflected but replacements only take place with key mapping. Using pandas replace I was able to do it all in 1 go without looping, so that's why I chose it.  Also this null value comes in as I'm reading it from a csv file. Its an empty sting in the original doc so that's why I went ahead. Still I'm open to suggestions as I don't really like the fact that null is not getting transformed so please do let me know if there are any other methods.
@VishalECC hope to get your suggestions too.

2021-02-17 20:30 UTC, mattdrayer approved these changes

2021-02-17 20:31 UTC, KarenAJ approved these changes

2021-02-17 20:32 UTC, merged