Feature/api call to xis
OpenLXP/openlxp-xia-dau pull request #6
Opened 2021-02-23 21:07 UTC by SHGODE

@mattdrayer 
Hi Matt, Opening a WIP pull request.  Can you please take a look at it and suggest changes in load_target_metadata if any?
I have commented a few lines of code as Validate functionality on XIS is WIP, once that is done we can uncomment code and change accordingly.

2021-02-24 18:54 UTC, mattdrayer requested changes

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +# from django.utils import timezone
We can remove this disabled import  if it is not necessary

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    api_endpoint = "http://openlxp-xis-load:8020/api/metadata/"
Docstring would be good to include

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    api_endpoint = "http://openlxp-xis-load:8020/api/metadata/"
In addition this endpoint should be pulled from either config (Django admin) or settings

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    MetadataLedger.objects.filter(
I don't believe that using `.filter()` results in a commit of state..  Filtering is used for retrieving a batch of records from the database.  You might want to look into .save()

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    #logger.info('XIS response after Validation'
Remove hidden code if unnecessary.

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    # MetadataLedger.objects.filter(
Remove hidden code if unnecessary -- see comment above re: filter vs. save.

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +                    "available in XIA to transmit")
Is there any sort of action we need the system to take if no matches are found?  For example do we trigger an upstream process/workflow?

2021-02-24 18:54 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +        post_data_to_xis()
It would be good to combine these two commands into a single command, if they are tightly-coupled, versus calling them separately.

2021-02-24 18:54 UTC, mattdrayer commented on docker-compose.yml
> +  db_xia:
Since this database is very specific to the DAU XIA, I think we probably should name it `db_xia_dau`

2021-02-24 18:54 UTC, mattdrayer commented on docker-compose.yml
> +  app_xia:
Since this app is very specific to the DAU XIA, I think we probably should name it `app_xia_dau`

2021-02-24 18:54 UTC, mattdrayer commented on docker-compose.yml
> +    external: true
Need a newline

2021-02-24 18:59 UTC, SHGODE commented on app/core/management/commands/load_target_metadata.py
> +# from django.utils import timezone
I commented that one to use it once we uncomment the code after line 59 I am waiting for the validation part which is WIP.

2021-02-24 19:06 UTC, SHGODE commented on app/core/management/commands/load_target_metadata.py
> +                    "available in XIA to transmit")
Yeah, we can call extract_source_metadata from here. Will that make sense?

2021-02-24 19:11 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +                    "available in XIA to transmit")
Sure, that sounds like a good loop-back

2021-02-25 15:06 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    MetadataLedger.objects.filter(
I missed the chained `.update()` at the end -- looks like you are good to go here.

2021-02-25 15:07 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +        post_data_to_xis()
arg I realize now this is a recursive call back to itself -- ignore :)

2021-02-25 15:15 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +                    "available in XIA to transmit")
As discussed offline w/ @SHGODE we are NOT going to re-call `extract` after the `load` command finishes.

2021-03-01 16:59 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    data.update(dict_add_publisher)
Why do it this way instead of simply:

`data['provider_name'] = get_publisher_to_add()`

2021-03-01 17:05 UTC, mattdrayer requested changes

2021-03-01 17:05 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    data.update(dict_add_publisher)
Why do it this way instead of simply:

`data['provider_name'] = get_publisher_to_add()`

2021-03-01 17:05 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    data['metadata_key'] = data.pop('target_metadata_key')
It might be better to convert this implicit contract into a reference schema and pull from the schema service.

2021-03-01 17:05 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    uuid_val = data.get('unique_record_identifier')
you `pop`'ed this field from the dictionary above -- does that mean it is no longer available?

2021-03-01 17:05 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
> +    else:
It would be good to return the status code and any helpful error messages returned by the server along with the rest of the response.

2021-03-01 17:05 UTC, mattdrayer commented on app/core/management/utils/xsr_client.py
> +    api_endpoint = "http://openlxp-xis-load:8020/api/metadata/"
This should be moved into app config or environment variable.

2021-03-02 22:35 UTC, SHGODE reviewed
> Nit: Please alphabetize the model fields (eg, relocate to line 80)

Done

2021-03-03 03:35 UTC, mattdrayer approved these changes
Looks good!

2021-03-03 03:56 UTC, KarenAJ approved these changes
Approved!

2021-03-03 05:07 UTC, merged