Added XSR XIA communication using DAU API
OpenLXP/openlxp-xia-dau pull request #9
Opened 2021-03-17 21:13 UTC by KarenAJ

@OpenLXP/contributors Added XSR XIA communication using DAU API and added additional condition for loading data to XIS from XIA. 
Please review the code!

2021-03-17 23:15 UTC, mattdrayer requested changes

2021-03-17 23:15 UTC, mattdrayer commented on app/core/management/utils/xsr_client.py
> +    # print(xsr_items)
We should remove this hidden/commented code before merging

2021-03-17 23:15 UTC, mattdrayer commented on app/core/management/utils/xsr_client.py
> +    url = 'https://icatalog.dau.edu/CatalogService.asmx/GetCourseDetails'
This should be moved into configuration

2021-03-17 23:15 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
>          if xis_response.status_code == 201:
I think it would be good to introduce an `xis_client.py` module similar to `xsr_client.py` which handles the direct communication with the XIS component -- this would make it easy to wrap communications in try/except blocks, raise SystemExit events, etc.

2021-03-17 23:15 UTC, mattdrayer commented on app/core/management/commands/load_target_metadata.py
>      data.update(dict_add_publisher)
Could this be revised to:

`data['provider_name'] = get_publisher_to_add()`  ?

2021-03-18 15:58 UTC, KarenAJ commented on app/core/management/commands/load_target_metadata.py
>          if xis_response.status_code == 201:
@SHGODE

2021-03-18 15:58 UTC, KarenAJ commented on app/core/management/commands/load_target_metadata.py
>      data.update(dict_add_publisher)
@SHGODE

2021-03-18 16:54 UTC, mattdrayer commented
`schema_client.py` --> `xss_client.py`

2021-03-21 00:21 UTC, mattdrayer approved these changes
This is coming together nicely!

2021-03-21 00:51 UTC, SHGODE approved these changes
Looks good!

2021-03-22 14:08 UTC, merged